apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgvector-cluster
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Sean-Michael/home-kubernetes-cloud.git
      targetRevision: HEAD
      path: applications/cloudnativepg
      directory:
        include: "pgvector.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgvector-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sean-Michael/home-kubernetes-cloud.git
    targetRevision: HEAD
    path: applications/cloudnativepg
    directory:
      include: "dashboard.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
